### PR TITLE
Fixes #4: Adding a splash screen for SUSI

### LINKED ISSUE #4: Add a splash screen
When the susi app starts up, it should show a welcome screen which disappears after three seconds. After that, the chat screen should be shown.

### PR DESCRIPTION
**Pull request by jig08**
... wrt issue #4 

screen shot 2016-08-21 at 9 32 24 pm

### CODE REVIEW

**Comment by sudheesh001** [comment]
Is the concentric circles a part of the splash screen, if so why is it there as a part of the design, also why not center aligned ? it looks off being at that awkward side

**Comment by shivenmian** [comment]
This code is way too complicated. You don't even need to do all this. You just need one handler and you're done.

```java

@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.splash_screen);

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                Intent intent = new Intent(SplashScreen.this, MainActivity.class);
                startActivity(intent);
                SplashScreen.this.finish();
            }
        }, 1000);
    }
```

That's all. I see you've implemented too many Handlers, or maybe you've taken this up from somewhere, but that's not the way to go about it.

**Comment by jig08** [comment]
>Is the concentric circles a part of the splash screen, if so why is it there as a part of the design, also why not center aligned ? it looks off being at that awkward side

@sudheesh001 That's the touch representation and not a design part.

**Comment by jig08** [comment]
>@jig08 This code is way too complicated. You don't even need to do all this. I see you've implemented too many Handlers, or maybe you've taken this up from somewhere, 

@shivenmian  Could be, I had been using this method to implement Splash Screens in my apps and not "taken this up from somewhere" .

You could go ahead and un-complicate this, if you feel so 😃

**Comment by shivenmian** [comment]
Yes I know what the code does. I'm not sure what a user is gonna do with the animation of that image really, and I already un-complicated it for you. But np it's okay.

**Comment by jig08** [comment]
Sure, we can always go the route without the animation. 
Thanks @shivenmian 👍

**Comment by jig08** [comment]
@Orbiter Let know if a non-animated version is required, it can always be changed to that ..

**Comment by sudheesh001** [comment]
@jig08 Alright, It looks like we can do away with the animations on a splash screen, it's generally expected to stay up on the screen for less than a second, investing time and effort into the splashscreen to animate it isn't really a viable option.

**Comment by jig08** [comment]
@sudheesh001 Okay, shall change to the non-animated version

**Comment by shivenmian** [comment]
@jig08 You tested it right?

**Comment by jig08** [comment]
@shivenmian Yes, I did test it and as you can see, I have changed the `duration` too... so It is well tested :)

**Comment by shivenmian** [comment]
Then it is good to go. I can't merge it as I do not have merge rights. @Orbiter can merge it.

**Comment by Orbiter** [comment]
thank you, works great!

**Pull request merged**
